import streamlit as st
import pandas as pd
import plotly.express as px

st.set_page_config(
    page_title="Sales Forecasting Dashboard",
    page_icon="📊",
    layout="wide"
)

@st.cache_data
def load_data():

    df = pd.read_csv("train.csv")

    df["Order Date"] = pd.to_datetime(
        df["Order Date"],
        format="%d/%m/%Y"
    )

    df["Year"] = df["Order Date"].dt.year

    df["Month"] = df["Order Date"].dt.strftime("%b")

    return df

df = load_data()


page = st.sidebar.radio(

    "Dashboard Menu",

    [

        "Sales Overview",

        "Forecast Explorer",

        "Anomaly Report",

        "Product Demand Segments"

    ]

)
if page == "Sales Overview":

    # -------------------------------------------------------
    # Dashboard Title
    # -------------------------------------------------------

    st.title("📊 Sales Forecasting Dashboard")
    st.markdown("### Sales Overview Dashboard")

    # -------------------------------------------------------
    # Sidebar Filters
    # -------------------------------------------------------

    st.sidebar.title("Filters")

    selected_region = st.sidebar.multiselect(

        "Select Region",

        options=df["Region"].unique(),

        default=df["Region"].unique()

    )

    selected_category = st.sidebar.multiselect(

        "Select Category",

        options=df["Category"].unique(),

        default=df["Category"].unique()

    )

    filtered_df = df[

        (df["Region"].isin(selected_region)) &

        (df["Category"].isin(selected_category))

    ]

    # -------------------------------------------------------
    # KPI Cards
    # -------------------------------------------------------

    total_sales = filtered_df["Sales"].sum()

    total_orders = filtered_df["Order ID"].nunique()

    total_customers = filtered_df["Customer ID"].nunique()

    col1, col2, col3 = st.columns(3)

    col1.metric("Total Sales", f"${total_sales:,.0f}")

    col2.metric("Total Orders", total_orders)

    col3.metric("Total Customers", total_customers)

    st.markdown("---")

    # -------------------------------------------------------
    # Total Sales by Year
    # -------------------------------------------------------

    yearly_sales = (

        filtered_df

        .groupby("Year")["Sales"]

        .sum()

        .reset_index()

    )

    fig_year = px.bar(

        yearly_sales,

        x="Year",

        y="Sales",

        title="Total Sales by Year",

        text_auto=".2s"

    )

    st.plotly_chart(fig_year, use_container_width=True)

    # -------------------------------------------------------
    # Monthly Sales Trend
    # -------------------------------------------------------

    monthly_sales = (

        filtered_df

        .groupby(pd.Grouper(key="Order Date", freq="ME"))["Sales"]

        .sum()

        .reset_index()

    )

    fig_month = px.line(

        monthly_sales,

        x="Order Date",

        y="Sales",

        markers=True,

        title="Monthly Sales Trend"

    )

    st.plotly_chart(fig_month, use_container_width=True)

    # -------------------------------------------------------
    # Sales by Region and Category
    # -------------------------------------------------------

    region_sales = (

        filtered_df

        .groupby("Region")["Sales"]

        .sum()

        .reset_index()

    )

    category_sales = (

        filtered_df

        .groupby("Category")["Sales"]

        .sum()

        .reset_index()

    )

    left, right = st.columns(2)

    with left:

        fig_region = px.pie(

            region_sales,

            names="Region",

            values="Sales",

            title="Sales by Region"

        )

        st.plotly_chart(fig_region, use_container_width=True)

    with right:

        fig_category = px.bar(

            category_sales,

            x="Category",

            y="Sales",

            title="Sales by Category",

            text_auto=".2s"

        )

        st.plotly_chart(fig_category, use_container_width=True)

elif page == "Forecast Explorer":

    st.title("📈 Forecast Explorer")

    st.markdown("Explore the sales forecast generated by the best performing XGBoost model.")

    forecast_df = pd.read_csv("forecast_results.csv")

    col1, col2 = st.columns(2)

    with col1:
        forecast_type = st.selectbox(
            "Select Forecast Type",
            forecast_df["Type"].unique()
        )

    filtered = forecast_df[
        forecast_df["Type"] == forecast_type
    ]

    with col2:
        selected_name = st.selectbox(
            "Select Category / Region",
            filtered["Name"]
        )

    horizon = st.slider(
        "Forecast Horizon (Months)",
        min_value=1,
        max_value=3,
        value=3
    )

    selected = filtered[
        filtered["Name"] == selected_name
    ].iloc[0]

    forecast_values = [
        selected["Month 1 Forecast"],
        selected["Month 2 Forecast"],
        selected["Month 3 Forecast"]
    ]

    months = [
        "Month 1",
        "Month 2",
        "Month 3"
    ]

    chart = pd.DataFrame({
        "Month": months[:horizon],
        "Forecast Sales": forecast_values[:horizon]
    })

    fig = px.line(
        chart,
        x="Month",
        y="Forecast Sales",
        markers=True,
        title=f"Sales Forecast for {selected_name}"
    )

    st.plotly_chart(
        fig,
        use_container_width=True
    )

    st.subheader("Forecast Values")

    st.dataframe(
        chart,
        use_container_width=True
    )

    metric1, metric2 = st.columns(2)

    with metric1:
        st.metric(
            "Model MAE",
            f"{selected['MAE']:.2f}"
        )

    with metric2:
        st.metric(
            "Model RMSE",
            f"{selected['RMSE']:.2f}"
        )

    st.success(
        "The XGBoost model was selected because it achieved the lowest forecasting error among all evaluated models."
    )

elif page == "Anomaly Report":

    st.title("🚨 Anomaly Report")

    st.markdown(
        "Identify unusual weekly sales detected using Isolation Forest and Z-Score methods."
    )

    # -------------------------------------------------------
    # Loading anomaly data
    # -------------------------------------------------------

    anomaly_df = pd.read_csv("anomaly_results.csv")

    anomaly_df["Week"] = pd.to_datetime(anomaly_df["Week"])

    # -------------------------------------------------------
    # Filter
    # -------------------------------------------------------

    methods = ["All"] + list(anomaly_df["Detection"].unique())

    selected_method = st.selectbox(
        "Select Detection Method",
        methods
    )

    if selected_method == "All":

        filtered = anomaly_df

    else:

        filtered = anomaly_df[
            anomaly_df["Detection"] == selected_method
        ]

    # -------------------------------------------------------
    # Summary Cards
    # -------------------------------------------------------

    col1, col2 = st.columns(2)

    col1.metric(
        "Total Anomalies",
        len(filtered)
    )

    col2.metric(
        "Highest Sales Anomaly",
        f"${filtered['Sales'].max():,.0f}"
    )

    st.markdown("---")

    # -------------------------------------------------------
    # Interactive Chart
    # -------------------------------------------------------

    fig = px.scatter(

        filtered,

        x="Week",

        y="Sales",

        color="Detection",

        hover_data=["Detection"],

        title="Detected Weekly Sales Anomalies"

    )

    st.plotly_chart(
        fig,
        use_container_width=True
    )

    # -------------------------------------------------------
    # Table
    # -------------------------------------------------------

    st.subheader("Detected Anomalies")

    st.dataframe(
        filtered,
        use_container_width=True
    )

    # -------------------------------------------------------
    # Business Insights
    # -------------------------------------------------------

    st.subheader("Business Insights")

    st.markdown("""

- **Isolation Forest** detects anomalies using a machine learning approach.

- **Z-Score** detects statistically unusual sales weeks.

- Anomalies identified by **both methods** are the strongest candidates for further investigation.

- High sales anomalies may indicate promotional campaigns, festive seasons or special offers.

- Low sales anomalies may indicate inventory shortages, reduced customer demand or supply chain issues.

""")

elif page == "Product Demand Segments":

    st.title("📦 Product Demand Segments")

    st.markdown(
        "Explore product demand clusters created using K-Means Clustering."
    )

    # -------------------------------------------------------
    # Loading Cluster Data
    # -------------------------------------------------------

    cluster_df = pd.read_csv("cluster_results.csv")

    # -------------------------------------------------------
    # Summary Cards
    # -------------------------------------------------------

    col1, col2 = st.columns(2)

    col1.metric(
        "Total Sub-Categories",
        cluster_df["Sub-Category"].nunique()
    )

    col2.metric(
        "Total Demand Groups",
        cluster_df["Demand Group"].nunique()
    )

    st.markdown("---")

    # -------------------------------------------------------
    # Demand Group Filter
    # -------------------------------------------------------

    demand_groups = ["All"] + list(cluster_df["Demand Group"].unique())

    selected_group = st.selectbox(
        "Select Demand Group",
        demand_groups
    )

    if selected_group == "All":

        filtered = cluster_df

    else:

        filtered = cluster_df[
            cluster_df["Demand Group"] == selected_group
        ]

    # -------------------------------------------------------
    # PCA Scatter Plot
    # -------------------------------------------------------

    fig = px.scatter(

        filtered,

        x="PCA1",

        y="PCA2",

        color="Demand Group",

        hover_name="Sub-Category",

        size="Total Sales",

        title="Product Demand Clusters"

    )

    st.plotly_chart(
        fig,
        use_container_width=True
    )

    # -------------------------------------------------------
    # Cluster Table
    # -------------------------------------------------------

    st.subheader("Product Demand Segments")

    st.dataframe(

        filtered[
            [
                "Sub-Category",
                "Demand Group",
                "Total Sales",
                "Growth Rate",
                "Volatility",
                "Average Order Value"
            ]
        ],

        use_container_width=True

    )

    # -------------------------------------------------------
    # Stocking Strategy
    # -------------------------------------------------------

    st.subheader("Recommended Stocking Strategy")

    st.markdown("""

### 🟢 High Volume, Stable Demand
- Maintain high inventory levels.
- These products contribute significantly to overall sales.
- Avoid stock-outs.

---

### 🔵 Growing Demand
- Gradually increase inventory.
- Monitor demand trends regularly.
- Plan replenishment in advance.

---

### 🟠 Low Volume, High Volatility
- Maintain moderate inventory.
- Review sales frequently.
- Avoid excessive stock.

---

### 🔴 Declining Demand
- Reduce inventory.
- Avoid overstocking.
- Consider promotional offers to clear inventory.

""")

    # -------------------------------------------------------
    # Business Insights
    # -------------------------------------------------------

    st.subheader("Business Insights")

    st.markdown("""

- Products were grouped using **Total Sales**, **Growth Rate**, **Sales Volatility**, and **Average Order Value**.

- K-Means clustering divided products into meaningful demand segments.

- PCA reduced multiple features into two dimensions for easier visualization.

- This segmentation helps inventory managers decide which products should be stocked aggressively and which require cautious planning.

""")



